### ISSUE TITLE
Tela Principal

### ISSUE THREAD

**Issue by Vidottolv** [Vidottolv/EzPrice#1]
Deixar a tela principal mais organizada, para que não fique toda cheia de infos desorganizadas (quanto à maneira que iremos alocar os widgets na tela, fica em aberto, vamos no nosso feeling)
![Issue-EstilizarEntrada](https://user-images.githubusercontent.com/89951349/231910068-c9f74e6f-c086-4b0f-adfc-b8c62fc6f35d.png)

**Comment by Jbnado** [comment]
It's done

**Comment by Jbnado** [comment]
Feito!
