### ISSUE TITLE
Esqueceu a Senha

### ISSUE THREAD

**Issue by Vidottolv** [Vidottolv/EzPrice#2]
Precisamos ajustar esta tela, para fazermos a recuperação de senha. Por exemplo, ao invés de já recriar a senha dentro do próprio app, podemos fazer o esquema de passarmos o email vinculado e, no email, ter o link para criarmos a nova senha (podemos até mesmo contar como mais uma funcionalidade)

nesse caso, ao invés de deixarmos os dois widgets de senha, podemos só passar um input de email e um botão de confirmar

![image](https://user-images.githubusercontent.com/89951349/231910124-e4942206-a0ec-4378-a667-1c4ad2f3d940.png)

**Comment by Jbnado** [comment]
O problema é que necessitamos do email para recuperar, então o esqueceu sua senha seriam 2 telas, uma pedindo o email e outra para o link que o email enviará para recuperar que no caso será essa da issue.

**Comment by Jbnado** [comment]
Feito!
