### ISSUE TITLE
cadastro de usuário

### ISSUE THREAD

**Issue by Vidottolv** [Vidottolv/EzPrice#4]
no cadastro de usuário, coloquei estes inputs até agora. Caso lembremos de outras informações, podemos adicioná-las. Inclusive, caso tenhamos uma ideia que deixe o layout melhor (sem deixar input abaixo de input), podemos implementá-la

![image](https://user-images.githubusercontent.com/89951349/231910702-5327022d-5fd8-4fd0-8643-613e01f0cd0d.png)

**Comment by Jbnado** [comment]
Feito!
