### ISSUE TITLE
Layout Geral

### ISSUE THREAD

**Issue by Vidottolv** [Vidottolv/EzPrice#7]
Não tenho certeza se a mesclagem de cores está sendo adequada. Caso pensemos em alguma cor que fique melhor em algum widget e/ou textos, vamos fazê-lo.
Talvez utilizar letras brancas? não sei
![image](https://user-images.githubusercontent.com/89951349/231910982-6f03101d-5b58-4c18-9691-7bdc55363503.png)

**Comment by Jbnado** [comment]
Podemos utilizar letra branca, isso já resolve

**Comment by Jbnado** [comment]
O layout geral está finalizado! Ficou faltando apenas a tela de precificação e as telas subsequentes a ela como gerar uma nova precificação, também teremos que pensar na edição das informações das receitas e ingredientes, mas acredito que isso alinhado com o banco de dados fica mais fácil de planejar.
